version: '3'
services:
  postgres:
    image: postgres:14.1
    restart: always
    volumes:
      - "/Users/anishsinha/Home/docker/Volumes/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    image: nginx:1.21.6
    depends_on:
      - api
      - client
    restart: always
    ports:
      - "3050:80"
    build: ./nginx

  api:
    build: ./server
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=host.docker.internal
      - POSTGRES_HOST=${POSTGRES_HOST}
    expose:
      - 8000
    ports:
      - "8000:8000"
    

  client:
    stdin_open: true
    build: ./client
    volumes:
      - /app/node_modules
      - "./client:/app"
    
      
