version: '3'
services:
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  client:
    image: anishsinha1/lifeofanish-client:1.0.1
    stdin_open: true

  api:
    image: anishsinha1/lifeofanish-server:1.0.1
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SERVER_PORT=${SERVER_PORT}
  nginx:
    image: anishsinha1/lifeofanish-nginx:1.0.1
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 3050:80
  