version: '3'
services:
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  client:
    image: anishsinha1/lifeofanish-client
    stdin_open: true
    volumes: 
      - /app/node_modules
      - "./client:/app"
  api:
    image: anishsinha1/lifeofanish-server
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SERVER_PORT=${SERVER_PORT}
  nginx:
    image: anishsinha1/lifeofanish-nginx
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 3050:80
  