name: "Deploy to EBS"

on:
  push:
    branches:
      - main

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT}}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          directory: .
          file_name: .env
  
  build-images:
    name: build docker images and deploy to ebs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t anishsinha1/lifeofanish-client:1.0.1 ./client 
      - run: docker build -t anishsinha1/lifeofanish-server:1.0.1 ./server
      - run: docker build -t anishsinha1/lifeofanish-nginx:1.0.1 ./nginx
      - run: docker push anishsinha1/lifeofanish-client:1.0.1
      - run: docker push anishsinha1/lifeofanish-server:1.0.1
      - run: docker push anishsinha1/lifeofanish-nginx:1.0.1

      - name: generate deployment package
        run: zip -r deploy.zip *

      - name: Deploy final to elastic beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: lifeofanish
          environment_name: lifeofanish-env
          existing_bucket_name: elasticbeanstalk-us-east-1-697480332228
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip